---
# Replacing default kibana.yml with updated file

- name: generate kibana config
  ansible.builtin.template:
    src: kibana.yml
    dest: /etc/kibana/kibana.yml

# Starting Kibana

- name: Starting Kibana
  systemd:
    name: kibana
    state: started
    enabled: yes