---

- name: download kibana
  get_url:
    url: https://artifacts.elastic.co/downloads/kibana/kibana-7.11.1-amd64.deb
    dest: "{{ kibana_download_path }}"
    checksum: sha512:https://artifacts.elastic.co/downloads/kibana/kibana-7.11.1-amd64.deb.sha512


- name: install kibana
  apt:
    deb: "{{ kibana_download_path }}"
