---

- name: download kibana
  get_url:
    url: https://artifacts.elastic.co/downloads/kibana/kibana-7.10.2-amd64.deb
    dest: "{{ elasticsearch_download_path }}"
    checksum: sha512:https://artifacts.elastic.co/downloads/kibana/kibana-7.10.2-amd64.deb.sha512

- name: install kibana
  apt:
    deb: "{{ kibana_download_path }}"

- name: delete downloaded package
  ansible.builtin.file:
    path: "{{ kibana_download_path }}"
    state: absent
